/**
 * Turns computed facts into Notion blocks.
 *
 * Each generated section starts with a marker paragraph so a re-run can find
 * and remove what the previous run wrote, instead of stacking duplicates.
 */

import { formatDay, weekdayName } from './util/date.js';

export const MARKER = 'generated by weekly-review';

const MAX_RICH_TEXT = 1900;

/* ---------------------------- block builders ---------------------------- */

export function text(content, annotations = {}) {
  return { type: 'text', text: { content: String(content).slice(0, MAX_RICH_TEXT) }, annotations };
}

export function paragraph(richText) {
  return {
    object: 'block',
    type: 'paragraph',
    paragraph: { rich_text: Array.isArray(richText) ? richText : [text(richText)] },
  };
}

export function bullet(richText) {
  return {
    object: 'block',
    type: 'bulleted_list_item',
    bulleted_list_item: { rich_text: Array.isArray(richText) ? richText : [text(richText)] },
  };
}

export function numbered(richText) {
  return {
    object: 'block',
    type: 'numbered_list_item',
    numbered_list_item: { rich_text: Array.isArray(richText) ? richText : [text(richText)] },
  };
}

export function callout(emoji, richText, color = 'gray_background') {
  return {
    object: 'block',
    type: 'callout',
    callout: {
      icon: { type: 'emoji', emoji },
      color,
      rich_text: Array.isArray(richText) ? richText : [text(richText)],
    },
  };
}

export function heading(content) {
  return {
    object: 'block',
    type: 'heading_3',
    heading_3: { rich_text: [text(content)] },
  };
}

/** Split long prose into paragraphs that fit inside one rich-text object. */
export function prose(content) {
  if (!content) return [];
  return String(content)
    .split(/\n{2,}/)
    .map((chunk) => chunk.trim())
    .filter(Boolean)
    .flatMap((chunk) => {
      const pieces = [];
      for (let index = 0; index < chunk.length; index += MAX_RICH_TEXT) {
        pieces.push(paragraph(chunk.slice(index, index + MAX_RICH_TEXT)));
      }
      return pieces;
    });
}

export function markerBlock(generatedAt) {
  return paragraph([
    text(`${MARKER} · ${generatedAt}`, { italic: true, color: 'gray' }),
  ]);
}

/* ------------------------------ formatting ------------------------------ */

const dash = '—';

function num(value, { unit = '', digits = 0, signed = false } = {}) {
  if (value === null || value === undefined || !Number.isFinite(value)) return dash;
  const rounded = Number(value).toFixed(digits);
  const sign = signed && value > 0 ? '+' : '';
  return `${sign}${rounded}${unit ? ` ${unit}` : ''}`;
}

function gradeText(grades) {
  const entries = [
    ['Fat loss', grades.fatLoss],
    ['Protein', grades.protein],
    ['Fibre', grades.fibre],
    ['Logging', grades.logging],
    ['Overall', grades.overall],
  ].filter(([, grade]) => grade);
  return entries.map(([label, grade]) => `${label} ${grade}`).join(' · ') || dash;
}

/* ------------------------- deterministic fallbacks ----------------------- */

export function fallbackNutritionProse(facts) {
  const parts = [];
  parts.push(`You are ${facts.verdict} against the ${facts.goal.targetWeightKg} kg goal.`);
  if (facts.intake.avgCaloriesPerLoggedDay !== null) {
    parts.push(`You averaged ${num(facts.intake.avgCaloriesPerLoggedDay)} kcal across ${facts.logging.daysWithEntries} logged day(s), ${facts.balance.position}.`);
  }
  if (!facts.logging.complete) {
    parts.push(`Only ${facts.logging.daysWithEntries} of ${facts.logging.ofDays} days have food entries, so treat the averages as indicative.`);
  }
  parts.push('Next week: log every day, hit protein first, and keep the deficit steady.');
  return parts.join(' ');
}

export function fallbackProgressProse(facts) {
  return `You are heading into ${facts.nextWeek.label}. `
    + `${facts.year.elapsedPercent}% of ${facts.year.year} has gone, with ${facts.year.remainingDays} days left. `
    + `${facts.season.current} runs until ${formatDay(facts.season.nextStartsOn)}.`;
}

export function fallbackMeetingsProse(facts) {
  if (!facts.available) return facts.reason;
  if (!facts.counts.included) return 'No notable external meetings are scheduled for next week.';
  return `${facts.counts.included} notable meeting(s) next week; `
    + `${facts.counts.excluded} routine or declined entries were filtered out.`;
}

export function fallbackTasksProse(facts) {
  return `${facts.counts.substantive} substantive task(s) due in the next seven days, `
    + `plus ${facts.counts.routine} routine item(s). `
    + `That is ${facts.realism.substantivePerWorkingDay} per working day — a ${facts.realism.load} week.`;
}

/* ------------------------------- sections ------------------------------- */

export function renderNutrition(facts, proseText, generatedAt) {
  const verdictEmoji = { 'on track': '✅', 'slightly behind': '⚠️', 'off track': '🔴' }[facts.verdict] ?? 'ℹ️';
  const blocks = [markerBlock(generatedAt)];

  blocks.push(callout(
    verdictEmoji,
    `${facts.verdict.toUpperCase()} · 7-day average ${num(facts.weight.periodAverage, { unit: 'kg', digits: 2 })} · `
    + `${num(facts.goal.kgToGo, { unit: 'kg', digits: 2 })} to go by ${formatDay(facts.goal.deadline)} (${facts.goal.daysToDeadline} days)`,
  ));

  blocks.push(bullet(
    `Intake: ${num(facts.intake.avgCaloriesPerLoggedDay)} kcal/day across ${facts.logging.daysWithEntries}/${facts.logging.ofDays} logged days `
    + `${dash} ${facts.balance.position}`,
  ));

  blocks.push(bullet([
    text('Maintenance: '),
    text(num(facts.targets.maintenanceKcal, { unit: 'kcal' }), { bold: true }),
    text(` (${facts.targets.provenance.maintenanceKcal?.description ?? 'source unknown'})`
      + `${facts.targets.targetKcal !== null ? ` · daily target ${num(facts.targets.targetKcal, { unit: 'kcal' })}` : ''}`),
  ]));

  blocks.push(bullet(
    `Protein ${num(facts.intake.avgProteinG, { unit: 'g', digits: 1 })}/day`
    + `${facts.targets.proteinTargetG ? ` of ${num(facts.targets.proteinTargetG, { unit: 'g' })}` : ''} · `
    + `Fibre ${num(facts.intake.avgFibreG, { unit: 'g', digits: 1 })}/day`
    + `${facts.targets.fibreTargetG ? ` of ${num(facts.targets.fibreTargetG, { unit: 'g' })}` : ''}`,
  ));

  blocks.push(bullet(
    `Weight: latest ${num(facts.weight.latest?.kg, { unit: 'kg', digits: 2 })}`
    + `${facts.weight.latest ? ` on ${formatDay(facts.weight.latest.day)}` : ''} · `
    + `trend ${facts.weight.direction} at ${num(facts.weight.observedKgPerWeek, { unit: 'kg/week', digits: 2, signed: true })} `
    + `(${facts.weight.readingsInTrend} readings over ${facts.weight.trendWindowDays} days)`,
  ));

  blocks.push(bullet(
    `Predicted from intake: ${num(facts.balance.predictedKgPerWeek, { unit: 'kg/week', digits: 2, signed: true })} · `
    + `observed: ${num(facts.weight.observedKgPerWeek, { unit: 'kg/week', digits: 2, signed: true })} `
    + `${dash} ${facts.crossCheck.note}`,
  ));

  if (facts.milestones.lastPassed) {
    const milestone = facts.milestones.lastPassed;
    blocks.push(bullet(
      `Milestone just passed (${formatDay(milestone.due)}): target ${num(milestone.targetKg, { unit: 'kg', digits: 1 })} `
      + `${dash} ${milestone.met === null ? 'no weight data' : milestone.met ? 'met ✅' : `missed by ${num(milestone.gapKg, { unit: 'kg', digits: 2 })}`}`,
    ));
  }
  if (facts.milestones.next) {
    const milestone = facts.milestones.next;
    blocks.push(bullet(
      `Next milestone (${formatDay(milestone.due)}, ${milestone.daysAway} days): `
      + `target ${num(milestone.targetKg, { unit: 'kg', digits: 1 })}, `
      + `${num(milestone.gapKg, { unit: 'kg', digits: 2 })} above it today`,
    ));
  }

  blocks.push(bullet([text('Grades: '), text(gradeText(facts.grades), { bold: true })]));
  blocks.push(...prose(proseText));
  return blocks;
}

export function renderProgress(facts, proseText, generatedAt) {
  const blocks = [markerBlock(generatedAt)];

  blocks.push(callout('📅', `${facts.nextWeek.label} · ${facts.nextWeek.range}`, 'blue_background'));
  blocks.push(bullet([
    text(`${facts.year.year}: `),
    text(facts.year.bar, { code: true }),
    text(` ${facts.year.elapsedPercent}% gone, ${facts.year.remainingPercent}% left `
      + `(${facts.year.remainingDays} days, ~${facts.year.weeksRemaining} weeks)`),
  ]));
  blocks.push(bullet(
    `${facts.season.current} since ${formatDay(facts.season.startedOn)} · `
    + `${facts.season.weeksUntilNext} weeks until ${facts.season.next} begins on ${formatDay(facts.season.nextStartsOn)}`,
  ));

  const extras = [`${facts.extras.workingDaysLeftInYear} working days left in the year`,
    `${facts.extras.mondaysLeftInYear} Mondays remaining`];
  if (facts.extras.nextHoliday) {
    extras.push(`${facts.extras.nextHoliday.daysAway} days to ${facts.extras.nextHoliday.name}`);
  }
  if (facts.extras.goalDeadline && !facts.extras.goalDeadline.passed) {
    extras.push(`${facts.extras.goalDeadline.daysAway} days to the ${formatDay(facts.extras.goalDeadline.day)} weight deadline`);
  }
  blocks.push(bullet(extras.join(' · ')));
  blocks.push(...prose(proseText));
  return blocks;
}

export function renderMeetings(facts, proseText, generatedAt, locale) {
  const blocks = [markerBlock(generatedAt)];

  if (!facts.available) {
    blocks.push(callout('🚧', facts.reason, 'yellow_background'));
    return blocks;
  }

  blocks.push(callout(
    '🤝',
    `${facts.counts.included} notable meeting(s), ${facts.window.start} to ${facts.window.end}`,
    'blue_background',
  ));

  for (const day of facts.days) {
    blocks.push(bullet([
      text(`${weekdayName(day.day, { locale })} ${formatDay(day.day, { locale, style: 'short' })}`, { bold: true }),
    ]));
    for (const meeting of day.meetings) {
      const organisations = meeting.externalOrganisations.length
        ? ` · ${meeting.externalOrganisations.join(', ')}`
        : '';
      blocks.push(bullet(
        `${meeting.startTime}–${meeting.endTime} ${meeting.title}`
        + `${meeting.location ? ` · ${meeting.location}` : ''}${organisations}`,
      ));
    }
  }

  if (facts.counts.excluded) {
    blocks.push(paragraph([
      text(`${facts.counts.excluded} routine, declined or all-day entries filtered out.`, { italic: true, color: 'gray' }),
    ]));
  }
  for (const problem of facts.problems) {
    blocks.push(callout('⚠️', problem, 'yellow_background'));
  }

  blocks.push(...prose(proseText));
  return blocks;
}

export function renderTasks(facts, proseText, generatedAt) {
  const blocks = [markerBlock(generatedAt)];

  blocks.push(callout(
    '🎯',
    `${facts.counts.substantive} substantive · ${facts.counts.routine} routine · `
    + `${facts.counts.overdue} overdue · ${facts.realism.load} week`,
    'green_background',
  ));

  if (facts.bigThree.length) {
    blocks.push(heading('Big three'));
    for (const item of facts.bigThree) {
      blocks.push(numbered(
        `${item.title}${item.project ? ` (${item.project})` : ''} · `
        + `${item.overdue ? 'OVERDUE, due' : 'due'} ${formatDay(item.due)}`,
      ));
    }
  }

  if (facts.byProject.length) {
    blocks.push(heading('By project'));
    for (const group of facts.byProject.slice(0, 6)) {
      blocks.push(bullet([
        text(`${group.project}: `, { bold: true }),
        text(`${group.count} item(s) — ${group.items.map((item) => item.title).join('; ')}`),
      ]));
    }
  }

  if (facts.overdue.length) {
    blocks.push(heading('Overdue / at risk'));
    for (const item of facts.overdue) {
      blocks.push(bullet(`${item.title} · ${item.daysLate} day(s) late`));
    }
  }

  blocks.push(paragraph([
    text(`${facts.counts.routine} routine item(s) across ${facts.realism.workingDays} working days `
      + `(${facts.realism.substantivePerWorkingDay} substantive per working day).`, { italic: true, color: 'gray' }),
  ]));

  blocks.push(...prose(proseText));
  return blocks;
}

/* ------------------------------- preview -------------------------------- */

/** Render blocks as plain text, so a dry run shows exactly what would be written. */
export function blocksToPreview(blocks, indent = '') {
  const lines = [];
  let ordinal = 0;
  for (const block of blocks) {
    if (block.type !== 'numbered_list_item') ordinal = 0;
    const content = block[block.type];
    const value = (content?.rich_text ?? []).map((run) => run.text.content).join('');
    switch (block.type) {
      case 'callout': lines.push(`${indent}${content.icon.emoji} ${value}`); break;
      case 'bulleted_list_item': lines.push(`${indent}  • ${value}`); break;
      case 'numbered_list_item': ordinal += 1; lines.push(`${indent}  ${ordinal}. ${value}`); break;
      case 'heading_3': lines.push(`${indent}### ${value}`); break;
      default: lines.push(`${indent}${value}`);
    }
  }
  return lines.join('\n');
}
